# Use the official Node.js 18 image as the base image
FROM node:18-alpine

# Install nodemon globally for development
RUN npm install -g nodemon tsx

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Install all dependencies (including dev dependencies) for development
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port that the application will run on
EXPOSE 3005

# Define the command to run the application in development mode
CMD [ "npm", "run", "dev" ]